version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
